services:
  authservice:
    image: ${DOCKER_REGISTRY-}authservice
    build:
      context: .
      dockerfile: AuthService/Dockerfile

  gatewayservice:
    image: ${DOCKER_REGISTRY-}gatewayservice
    build:
      context: .
      dockerfile: GatewayService/Dockerfile


  planservice:
    image: ${DOCKER_REGISTRY-}planservice
    build:
      context: .
      dockerfile: PlanService/Dockerfile


  taskservice:
    image: ${DOCKER_REGISTRY-}taskservice
    build:
      context: .
      dockerfile: TaskService/Dockerfile


  userservice:
    image: ${DOCKER_REGISTRY-}userservice
    build:
      context: .
      dockerfile: UserService/Dockerfile

